### ISSUE TITLE
Debug/Release builds

### ISSUE THREAD

**Issue by EtiennePasteur** [FocusCompany/daemon#26]
Add compiler-specific flags in case the requested build if of type `Release` or `Debug`. For now, all our builds are `Debug` ones.

This [link](https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/Useful-Variables) provide guidance on the correct way to do that.

Building with optimization wouldn't hurt, but ideally not by default.

**Comment by HippoBaro** [comment]
See #27
