### ISSUE TITLE
Switch build dependency management to Conan

### ISSUE THREAD

**Issue by HippoBaro** [FocusCompany/daemon#31]
### Problem

For build dependency-management we currently advise users (or use ourselves in CI):

- Native package managers on GNU/Linux
- `brew` on OSX
- `vcpkg` on Windows.

In all three cases, end users wishing to compile our software need to:

1. Be aware of our dependencies via the `README`
2. Compile and install the dependencies, or get pre-made packages if available
3. Pray for CMake to be able to detect them (and fail to do so, in the case of OpenSSL, for example).

This approach is troublesome. 

### Solution

**Conan is a cross-platform C++ package manager that integrates with CMake projects.**
Using something like that would allow us to streamline the build process on all platforms. Meaning the only build dependency required (apart from `build-essential` or platform equivalent) will be `Conan` itself.

Conan also provides added benefits like an advances option system that enables us to choose if we prefer the use an external library as static or via dynamic linkage, something that vanilla CMake usually has trouble doing. It also provides utility to copy dependency resources to a specific directory at build (for example, `dll`s). This is also something that CMake has trouble doing in a cross-platform way.

> Linking with static dependency is usually a very good idea because it enables us to ship a single binary without bothering with system-specific dynamic linking.

**Comment by ras0219-msft** [comment]
We've recently released vcpkg support for OSX and Linux; please try it out and let us know what doesn't work for you!

**Comment by EtiennePasteur** [comment]
I choose to keep vcpkg
